on:
  fork:
  push:
    branches: [develop]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h2>Hey, Welcome to this repo, Congratulations on opening your issue. Keep Contributing</h2>'
          pr-message: '<h2>Hey, Welcome to this repo, Congratulations on opening your Pull Requests. Keep Contributing</h2>'
          footer: '<h3>I will try to review your work and I will add it as soon as possible.</h2> <h4>Meanwhile, You can also Follow me on <a href="https://github.com/MrKrishnaAgarwal">GitHub</a>, and <a href="https://twitter.com/DMKrishnaA">Twitter</a> also Feel free to checkout my other cool <a href="https://github.com/MrKrishnaAgarwal?tab=repositories">repositories</a> and <a href="https://dev.to/krishnaagarwal">articles</a></h4>'
